# Change these first
owner: Skywt2003 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: SkyWT (China)
    url: https://skywt.cn
  - name: SkyWT (Global)
    url: https://skywt.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.skywt.net
  # baseUrl: /your-repo-name
  # logoUrl: https://blog.skywt.cn/usr/themes/sky/assets/avatar.png 
  name: Uptime
  introTitle: "Uptime status, powered by Github Actions & Upptime."
  introMessage: Here is uptime status of SkyWT's servers.
  navbar:
    - title: Uptime
      href: /
    - title: Home
      href: https://skywt.net
    - title: Status
      href: https://status.skywt.cn

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
